fh=open("output.txt","w")
val=input("Enter text to write to the file:")
fh.write(val)
fh.close()
fh=open("output.txt","a")
val=input("Enter additional text to append:")
fh.write(val)
fh.close()
fh=open("output.txt","r")
output=fh.read()
print(f"Final content of the output.txt: {output}")